# Generated by Django 2.2.1 on 2019-06-06 06:00

import apps.testimonial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=apps.testimonial.models.get_image_filename, verbose_name='Image')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('jobs', models.CharField(max_length=100)),
            ],
        ),
    ]
