# Generated by Django 2.2.1 on 2019-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
