# Generated by Django 2.2.1 on 2019-06-10 11:36

import apps.testimonial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_testimonial_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(help_text='Upload an image with 320 X 300 , size: 15.9 kB (15,856 bytes)', upload_to=apps.testimonial.models.get_image_filename, verbose_name='Image'),
        ),
    ]
