# Generated by Django 2.2.1 on 2019-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_auto_20190610_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Testimonials'},
        ),
    ]
