# Generated by Django 2.2.1 on 2019-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Person_images')),
                ('hov_image', models.ImageField(upload_to='media/Person_images')),
            ],
        ),
    ]
