# Generated by Django 2.2.1 on 2019-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
