# Generated by Django 2.2.1 on 2019-05-17 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20190517_0433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='phno',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='address',
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
