# Generated by Django 2.2.1 on 2019-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0013_auto_20190610_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
