# Generated by Django 2.2.1 on 2019-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0017_auto_20190610_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
