# Generated by Django 2.2.1 on 2019-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='any_field',
            field=models.BooleanField(default=False),
        ),
    ]
