# Generated by Django 2.2.1 on 2019-05-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_images_any_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='any_field',
            new_name='default_image',
        ),
    ]
