# Generated by Django 2.2.1 on 2019-06-10 11:36

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190603_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(help_text='Upload an image with 1000 x 667  , size: 40.7 kB (40,749 bytes)', upload_to=apps.products.models.get_image_filename, verbose_name='Image'),
        ),
    ]
