# Generated by Django 2.2.1 on 2019-06-10 12:02

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190610_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='hov_image',
            field=models.ImageField(default=None, help_text='Upload an image with 1000 x 667  , size: 40.7 kB (40,749 bytes)', upload_to=apps.products.models.get_image_filename, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
