# Generated by Django 2.2.1 on 2019-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_images_hov_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
