# Generated by Django 2.2.1 on 2019-06-03 06:53

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.home.models.get_image_filename, verbose_name='Image')),
            ],
        ),
    ]
