# Generated by Django 2.2.1 on 2019-06-10 11:15

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(help_text='Upload an image with 1326 x 635 ', upload_to=apps.home.models.get_image_filename, verbose_name='Image'),
        ),
    ]
