# Generated by Django 2.2.1 on 2019-06-10 11:36

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190610_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(help_text='Upload an image with 1920 x 920 , size: 58.8 kB (58,821 bytes) ', upload_to=apps.home.models.get_image_filename, verbose_name='Image'),
        ),
    ]
