# Generated by Django 2.2.1 on 2019-06-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
