# Generated by Django 2.2.1 on 2019-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(help_text='Upload an image with 170 x 160, size:  7.2 kB (7,205 bytes', upload_to='media/About_images'),
        ),
    ]
