# Generated by Django 2.2.1 on 2019-06-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_auto_20190610_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abou',
        ),
    ]
