# Generated by Django 2.2.1 on 2019-06-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20190614_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abou',
            new_name='About',
        ),
    ]
