# Generated by Django 2.2.1 on 2019-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_auto_20190614_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
    ]
